version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: tarunima
      POSTGRES_PASSWORD: tarunima
      POSTGRES_DB: bookmanagement
    ports:
      - "5432:5432"
    volumes:
      - postgres-b-data:/var/lib/postgresql/data

volumes:
  postgres-b-data:
    external: true
